### ISSUE TITLE
A better swipe to delete

### ISSUE THREAD

**Issue by slidenerd** [thorbenprimke/realm-recyclerview#1]
Hello thobenprimke, first of all , awesome efforts put into making something that works with Realm. Since you mentioned "What functionality are you missing? Open a Github issue and let me know." I thought I'd suggest an improvement.

I do notice that the item gets deleted on the screen when you swipe it, though its not that obvious yet. One of the first and simplest improvements you can do is to let people remove items using this https://developer.android.com/reference/android/support/v7/widget/helper/ItemTouchHelper.html from the RecyclerView , Here is a detailed usage guide https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf just in case. I am playing with the samples currently, if I find something I'll let you know. Thanks and keep up the good work

**Comment by thorbenprimke** [comment]
@slidenerd - Thanks for the pointers on the `ItemTouchHelper`. Based on the Medium article, it looks pretty simple to add (compared to when I added similar functionality to a ListView in the past).
I'll see about adding it.

**Comment by thorbenprimke** [comment]
hi @slidenerd - I added support for swipeToDelete and it landed in acfb002da790efe1c523316111d8826d970f7040. 
It's the simple implementation described in the Medium article but could be extended further to things like 'Undo' or ask for confirmation. 
I added it to the LinearLayout example and the To-Do app demo. 

What do you think?
