### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by marynovskyi** [thorbenprimke/realm-recyclerview#10]
I can't connect this library. When I try to connect with it (compile 'com.github.thorbenprimke:realm-recyclerview:0.9.7') in build.gradle I take error
When I try to find it in maven or anywhere also I have no results.

**Comment by Sirrah** [comment]
Have you added the Maven configuration from the Readme:

```
repositories {
        // ...
        maven { url "https://jitpack.io" }
}
```

This uses the Maven plugin to create a repository pointing to jitpack which is a means to include releases directly from GitHub.

If so, what is the error you receive?

**Comment by thorbenprimke** [comment]
Yes, as @Sirrah pointed out, you have to add `jitpack` to the repositories section of your project's `build.gradle` file.

**Comment by marynovskyi** [comment]
Yeah, I forget it, sorry) Thanks for your help guys
