### ISSUE TITLE
Remove refreshing animation

### ISSUE THREAD

**Issue by mikescamell** [thorbenprimke/realm-recyclerview#12]
Hi @thorbenprimke, i'm having an issue that i'm struggling to figure out with removing the refreshing animation.

Ok so i'll just do a quick explanation of what i'm doing. When the users pulls to refresh i check to see if they have a network connection and if they don't i show an error message along with realmRecyclerView.setRefreshing(false). This works great the first time, the error is shown and the animation gets removed. 

But when this is done a second time the animation is endless and the pull to refresh doesn't seem to trigger my onRefreshListener. I'm using an adapter with automatic updates set to true and i wonder if the fact my data has not changed has anything to do with it as i cannot seen why it would be a problem.

I have no such issues with it when i need to remove the animation when i have a network connection and i get data from my api. 

Thanks for your hardwork. I'll have a look at the source in the meantime to see if i can find anything.

**Comment by mikescamell** [comment]
Ok so i figured out that the realmRecyclerView.setRefreshing(false) is happening too quickly in my code. 
I'm guessing it is something to do with the animation only just starting and the speed at which the listener is triggered causing it to not be set to false correctly during the first call.

By adding a delay of 2 seconds to call realmRecyclerView.setRefreshing(false) the refresh animation removes successfully each time.

**Comment by vitas** [comment]
have the same issue, something wrong with it. 
I have empty adapter, by first refresh it works, by second attempt - endless refreshing animation.

**Comment by JamesMcIntosh** [comment]
Hi Mike, did you breakpoint the code and see the setRefreshing(false) was being called?

I have done a little bit of digging as I had the same problem too. From what I can see is the code  for the SwipeRefreshLayout.OnRefreshListener in RealmRecyclerView (hidden at the very bottom of the file) does not turn off the refreshing if the onRefreshListener is null.

If you do have a onRefreshListener set then make sure that it does actually call setRefreshing(false) at the expected time.

https://github.com/thorbenprimke/realm-recyclerview/blob/master/library/src/main/java/co/moonmonkeylabs/realmrecyclerview/RealmRecyclerView.java

I think a solution would be to update the listener as below:

```
recyclerViewRefreshListener = new SwipeRefreshLayout.OnRefreshListener() {
    @Override
    public void onRefresh() {
        if (!isRefreshing) {
            if (onRefreshListener == null) {
                swipeRefreshLayout.setRefreshing(false);
            } else {
                // listener is in charge of calling setRefreshing(false)
                onRefreshListener.onRefresh();
                isRefreshing = true;
            }
        }
    }
};
```

**Comment by mikescamell** [comment]
Hi @JamesMcIntosh,

Unfortunately the project i was doing this for has taken a back seat but it will come back around eventually. What you've written seems to make sense and I'll try and see if I can throw this in the project this weekend and confirm your solution. Thanks for posting, it's much appreciated.
