### ISSUE TITLE
Enhancement: Method to change empty layout in RealmRecyclerView

### ISSUE THREAD

**Issue by michbas796** [thorbenprimke/realm-recyclerview#16]
Could you add method to programmatically change empty layout in RealmRecyclerView?

**Comment by guilhermekrz** [comment]
+1

**Comment by usernotnull** [comment]
This would actually be the last possible improvement to make this library full. A method to get and set empty layouts. Sometimes the empty layouts need to show more information and I needed a way to change the text in a textview or swap a drawable programmatically.
