### ISSUE TITLE
hasLoadMoreFired never set back to false after loading more 

### ISSUE THREAD

**Issue by guillermomuntaner** [thorbenprimke/realm-recyclerview#19]
Right before onLoadMore() is triggered, the flag boolean hasLoadMoreFired is set to true to avoid calling this method several times. Problem is its never set to false again so onLoadMore() only is going to be called once.

Since it is a private member, it needs to be exposed so we can set it back to false when we finish the load of more data.

**Comment by itslonua** [comment]
I have this trouble too.
