### ISSUE TITLE
How to access addItemDecoration (To add line separators)? 

### ISSUE THREAD

**Issue by staydecent** [thorbenprimke/realm-recyclerview#20]
Hey, was just curious what the best way to go about adding decorations/line separators between each item in the `RecyclerView`?

I'm new to Java and Android, so I may be missing another solution that would work better in this situation. But, I came across these examples:
- https://gist.github.com/alexfu/0f464fc3742f134ccd1e
- https://gist.github.com/polbins/e37206fbc444207c0e92

However, in the case of `RealmRecyclerView` the `addItemDecoration` method is not exposed. My thinking was it could be exposed right about here: https://github.com/thorbenprimke/realm-recyclerview/blob/master/library/src/main/java/co/moonmonkeylabs/realmrecyclerview/RealmRecyclerView.java#L330

I'd be up for forking and adding a wrapper method to expose `addItemDecoration` but I am not sure about best practices in terms of variable arguments? Is method overloading the way to go? Or varargs?

Appreciate any help (and thanks for the great library!)

**Comment by vitas** [comment]
need the same! sent pullrequest

**Comment by valokafor** [comment]
Hi I need the same, and I was wonder if the pull request sent by @vitas  has been merged.

Thanks

Val

**Comment by CodeInvoker** [comment]
hope can be support for addItemDecoration
