### ISSUE TITLE
Access to LayoutManager - need setStackFromEnd()

### ISSUE THREAD

**Issue by grigoryfedorov** [thorbenprimke/realm-recyclerview#22]
Hi! Is there any way to get reversed items order (scroll from bottom to top)?
I used setStackFromEnd(true) for LayoutManager, but it is private here..

**Comment by StephenBrough** [comment]
:+1:

**Comment by dkpalmer** [comment]
I also need a method from the LayoutManager (findLastCompletelyVisibleItemPosition() for a LinearLayoutManager). It might be most convenient to just expose the LM?
