### ISSUE TITLE
Remove Pull Animation and make Setting Item Background working

### ISSUE THREAD

**Issue by clecb** [thorbenprimke/realm-recyclerview#23]
**(1)** I am setting my recycler item background to this: `android:background="?attr/selectableItemBackground"`. But it doesnt work when I click on one item.

**(2)** I am getting an animation when I am pulling down from the top but I havent set it refreshable. How can I turn this off?

![pull](https://cloud.githubusercontent.com/assets/17216196/13027360/6160a560-d24c-11e5-913e-7d32df744857.png)

**Comment by DanteAndroid** [comment]
Maybe you should use `android:foreground="?attr/selectableItemBackground"
` instead of "background"
