### ISSUE TITLE
cannot pull from jitpack - auth required

### ISSUE THREAD

**Issue by hardysim** [thorbenprimke/realm-recyclerview#25]
When adding this repo to gradle (as described in the README) I get the following error:

> Error:Could not GET 'https://jitpack.io/com/github/thorbenprimke/realm-recycler-view/0.9.13/realm-recycler-view-0.9.13.pom'. Received status code 401 from server: Repo not found or no access token provided
> <a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a>

Other repos from jitpack are working fine.
Can you please fix this?

**Comment by Mfrenchy77** [comment]
Same Problem I am having,
So, i changed the version to 0.9.12 and is working

**Comment by thorbenprimke** [comment]
Should be fixed now. 0.9.14 is out.

**Comment by carlbenson** [comment]
Cannot get any version, same error as original post. Tried 0.9.14 through .20

**Comment by carlbenson** [comment]
Ah, I copied the compile-line from your https://realm.io/news/android-recycler-view/ article where the repo is named `realm-recycler-view` when it should actually be `realm-recyclerview`

Works now!
