### ISSUE TITLE
Upgrade Realm to 0.88.X

### ISSUE THREAD

**Issue by dereklucas** [thorbenprimke/realm-recyclerview#29]
This is (probably) a big change since it Realm has changed to a gradle plugin. I'm starting to upgrade my app to 0.88.2 so as I do that, I'll take a stab at this as well. (Unless @Sirrah wants to!)
Unfortunately none of the other add-ons listed on Realm.io have upgraded to 0.88, so I don't see any similar libraries to cargo cult from.

**Comment by Sirrah** [comment]
My own project is nearing a stable release so I'm a bit more hesitant in upgrading dependencies. Still the 0.88 changes are very useful. I'll let you know when I've had an opportunity to look into it.

**Comment by eddiezane** [comment]
I could be totally wrong but for the time being I think you can include 0.88 and do:

``` gradle
    compile ('com.github.thorbenprimke:realm-recyclerview:0.9.13') {
        exclude group: 'io.realm', module: 'realm-android'
    }
```

**Comment by thorbenprimke** [comment]
0.9.14 is out and I upgraded Realm to 0.88. I apologize for the delay.
