### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Sol-Lim** [thorbenprimke/realm-recyclerview#30]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

apply plugin: 'com.android.application'
apply plugin: 'realm-android'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

```
defaultConfig {
    applicationId "com.company.suits.yourweek"
    minSdkVersion 19
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
}

buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support:recyclerview-v7:23.2.1'
    compile 'com.android.support:design:23.2.1'
    compile 'com.android.support:support-v4:23.2.1'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'joda-time:joda-time:2.9.2'
    compile 'com.github.thorbenprimke:realm-recyclerview:0.9.12'
}

**Comment by thorbenprimke** [comment]
Should be fixed. Upgrade to `0.9.20`.
