### ISSUE TITLE
How to customize Headers

### ISSUE THREAD

**Issue by weswes** [thorbenprimke/realm-recyclerview#31]
Hello,

What is the best way to customize headers ?

Thanks

**Comment by A86S** [comment]
@weswes & @thorbenprimke any update on this ?

**Comment by thorbenprimke** [comment]
@RJFares is this the customViewHeader issue that you mentioned on the other issue? 

Are y'all asking about the `addSectionHeaders` that are provided through `SuperSLiM` or the footer as shown in the `QuoteRecyclerViewAdapter`?

**Comment by usernotnull** [comment]
thanks for the quick reply I didn't have the chance to try it, but now I will since RealmModel is now supported....
I was referring to (quote) _There is currently no support for customizing the header_ in the readme file

**Comment by thorbenprimke** [comment]
@RJFares - Okay. For the `SuperSLiM` headers, there was a PR that added support for this. I haven't tried it myself but it should do what you are looking for. https://github.com/thorbenprimke/realm-recyclerview/pull/36

**Comment by usernotnull** [comment]
looks perfect!
