### ISSUE TITLE
clipToPadding="false" Is not working.

### ISSUE THREAD

**Issue by brunonmelo** [thorbenprimke/realm-recyclerview#33]
Hey everyone, I'm trying to add a paddind in the top and bottom and use the atribute clipToPadding="false" on xml to prevent my floating Action Button to overlap my RealmRecyclerView's information.
On the RecyclerView it's works okay, but it's don't seems to work on RealmRecyclerView.
It's a bug or I'm doing something wrong?

**Comment by hay12396** [comment]
Same issue here, i've also tried to programmatically set cliptopadding to false on the recyclerview that lives in RealmRecyclerView but it wont work.
