### ISSUE TITLE
Store context or expose it as a protected field or method

### ISSUE THREAD

**Issue by lujop** [thorbenprimke/realm-recyclerview#35]
**Use case**:
My implementation of adapter needs a context do decode resources for **createHeaderFromColumnValue()** implementation

The problem is that this method is called from super RealmBasedRecyclerViewAdapter constructor and I've no way to get it.

**Comment by thorbenprimke** [comment]
hi @lujop 

So I assume here that you are overriding `createHeaderFromColumnValue` in your `RealmBasedRecyclerViewAdapter` class? 
If that is the case, you could just provide a `Context` to your adapter implementation's constructor and then use it in your overridden `createHeaderFromColumnValue` method? 
Would that work for your use case?

**Comment by lujop** [comment]
Hi @thorbenprimke,
The problem is that `createHeaderFromColumnValue()` it's sometimes invoked from parent constructor before I'm able to store the context.

**Comment by thorbenprimke** [comment]
Aright. Let me add this use case to the example to figure out what's going
on.
