### ISSUE TITLE
Section headers?

### ISSUE THREAD

**Issue by teddywilson** [thorbenprimke/realm-recyclerview#39]
I'm having a really hard time trying to implement section headers with the realm recycler view.. Is there any chance you could upload an example? I'm looking to create different sections with separate realm queries.

**Comment by teddywilson** [comment]
I actually figured out how to do this. If anyone has any questions, don't hesitate to ask.

**Comment by ribhuchawla** [comment]
@teddywilson  Please share how to do it.
