### ISSUE TITLE
RealmModel support?

### ISSUE THREAD

**Issue by lwis** [thorbenprimke/realm-recyclerview#43]
Will you be supporting the RealmModel interface?

**Comment by thorbenprimke** [comment]
Yes, the change / switch to `RealmModel` should be pretty straight forward and I don't see why it shouldn't be changed. Using `RealmRecyclerView` with a `RealmObject` should still work since that class implements `RealmModel` as well.

**Comment by usernotnull** [comment]
any deadlines? I'm working on a project and I need to see if I'll implement your recyclerview.
Cheers!
(I hope the custom views for headers will also be implemented :) )

**Comment by thorbenprimke** [comment]
Commit 2835a543dce20993d8f98a4f773fa0e67132ce52 switches `RealmObject` for `RealmModel` in the adapter.

To try it out, update the gradle dependency to 

`compile 'com.github.thorbenprimke:realm-recyclerview:0.9.20'`

I also updated the TodoItem example's model to use `RealmModel`. A test with the example showed that adding and remove operations worked as expected. 

@lwis @RJFares let me know if this works for y'all.
