### ISSUE TITLE
java.lang.AbstractMethodError: abstract method "void io.realm.RealmChangeListener.onChange(java.lang.Object)"

### ISSUE THREAD

**Issue by puhgeh** [thorbenprimke/realm-recyclerview#44]
Please update compatibility with respect to the new Realm 0.90.0.

**Comment by dkpalmer** [comment]
Ran into this as well.

**Comment by dkpalmer** [comment]
Created a PR: https://github.com/thorbenprimke/realm-recyclerview/pull/45
