### ISSUE TITLE
Staggered Grid View Support

### ISSUE THREAD

**Issue by TheBoyMoe** [thorbenprimke/realm-recyclerview#46]
Hi Thorben, do you have any plans to add staggered grid view support?

**Comment by thorbenprimke** [comment]
Yea, I don't see anything preventing adding support for another LayoutManager. Are you referring to [StaggeredGridLayoutManager](http://developer.android.com/reference/android/support/v7/widget/StaggeredGridLayoutManager.html)?

**Comment by TheBoyMoe** [comment]
You bet!

**Comment by Farasy** [comment]
+1 for setLayoutManager() in order to set attributes like setReverseLayout() on LayoutManager.
