### ISSUE TITLE
IllegalArgumentException on ViewAdapter initialization when automaticUpdate false after 0.90 upgrade

### ISSUE THREAD

**Issue by drbourbon** [thorbenprimke/realm-recyclerview#47]
Hi,

updateRealmResults() method raises "java.lang.IllegalArgumentException: Listener should not be null" when RealmBasedRecyclerViewAdapter is initialized with automaticUpdate=false after 0.9.16 update.

**Comment by thorbenprimke** [comment]
hi @drbourbon - I have fixed this. It not checks that the listener is not null (which is the case if automaticUpdate is false). 

The fix in the the 0.9.20 release.
