### ISSUE TITLE
How to change ViewHolder type?

### ISSUE THREAD

**Issue by dimparf** [thorbenprimke/realm-recyclerview#48]
Hi
I make chat-like ui and use your awesome library for creating conversaion list.
How to change ViewHolder type on  onCreateRealmViewHolder or onBindRealmViewHolder? Example: recycleview with two type items - recived and sent message view (use different resources).

**Comment by dimparf** [comment]
Ok, i solve the problem.

**Comment by lawrence615** [comment]
Hi @dimparf, How did you solve this?

**Comment by dimparf** [comment]
@lawrence615 viewtype is one, but i am show or hide subviews on it depends on data from db.

**Comment by lawrence615** [comment]
@dimparf  two questions.

For this you had multiple view types (two I guess) but one ViewHolder? 

Have you implemented two or more ViewHolders in another project?

Thanks
