### ISSUE TITLE
 java.util.zip.ZipException: duplicate entry: io/realm/annotations/Ignore.class

### ISSUE THREAD

**Issue by sachin-shelke** [thorbenprimke/realm-recyclerview#51]
After adding dependancy along with io.realm dependancy, getting following error.

> Error:Execution failed for task ':App:transformClassesWithJarMergingForBetaBuildConfig'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: io/realm/annotations/Ignore.class

**Comment by thorbenprimke** [comment]
@sachin-shelke - Looks the cause for this error may be related to what's discussed in this issue: https://github.com/realm/realm-java/issues/1545. 

If you want to see an example of the Realm modules stuff, take a look at https://github.com/thorbenprimke/realm-nytimes-data and `GridExampleActivity` in the RealmRecyclerView example project.
