### ISSUE TITLE
Pull-to-refresh only works once.

### ISSUE THREAD

**Issue by VaibhavSavla** [thorbenprimke/realm-recyclerview#58]
I am using the following code to create a refresh listener
But this works only the first time. When I pull-to-refresh again the onRefresh() method is not called.
Am I doing something wrong.

```
mForecastRecyclerView.setOnRefreshListener(new RealmRecyclerView.OnRefreshListener() {
        @Override public void onRefresh() {
            Toast.makeText(activity, "Refreshing", Toast.LENGTH_LONG).show();

            // refresh work

            mForecastRecyclerView.setRefreshing(false);
        }
    });
```

**Comment by robsterthelobster** [comment]
I don't know if this solved, but I ran into this recently.

You have to wrap your call with AsyncTask or similar as seen in: [MainActivity.java](https://github.com/thorbenprimke/realm-recyclerview/blob/master/example/app/src/main/java/co/moonmonkeylabs/realmrecyclerview/example/MainActivity.java)

Here's my solution, though I'm not sure if I'm using RxJava properly:

```
  private void testRefresh() {
        Observable.just(0)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(s -> {
                    Toast.makeText(this, "Refresh", Toast.LENGTH_SHORT).show();
                    recyclerView.setRefreshing(false);
                });
    }
```

Then you just have the refreshlistener call the above method:

`recyclerView.setOnRefreshListener(() -> testRefresh());`

I had tried just making an Observable< Void > with similar results but the code is a lot cleaner with Observable.just();
