### ISSUE TITLE
Add Support For RealmRecyclerView To Support Height Wrap_Content

### ISSUE THREAD

**Issue by alextcn** [thorbenprimke/realm-recyclerview#63]
Hi. I tried to make not fixed height recycler view but as I understand RealmRecyclerView class doesn't work with `android:layout_height="wrap_content"`. Will you add this feature in the future?

**Comment by thorbenprimke** [comment]
Would this be for using the RealmRecyclerView with horizontal content? If so, #69 is in the works to add this support.

**Comment by alextcn** [comment]
No, It doesn't work with vertical view in my layout. Is it only mine problem?

**Comment by xaf-cv** [comment]
@SkyA1ex @thorbenprimke I have this issue with empty view layout.

Specifically, I have this as my empty view layout:

```
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <!-- Boring stuff here with text labels which require height to be set to wrap_content -->

</android.support.v7.widget.CardView>
```

As a result, RealmRecyclerView, when emtpy, gives me a card a size of match_parent, like this:

![capture1](https://cloud.githubusercontent.com/assets/12076257/17250974/66ded5e8-55af-11e6-8356-dad742c11540.PNG)

Whereas, I would expect it to look more like this:

![capture](https://cloud.githubusercontent.com/assets/12076257/17250965/5ed653e4-55af-11e6-84d0-0bd304b3b550.PNG)

**Comment by carlbenson** [comment]
@SkyA1ex I have this problem now too. `wrap_content` will effectively be `match_parent` anyway.
