### ISSUE TITLE
Is there a way to scroll to the top when I add new Item in the top

### ISSUE THREAD

**Issue by Khalid-Alqahtani** [thorbenprimke/realm-recyclerview#65]
Hello 

I use realm-recyclerview 

And I use .findAllSorted("date", Sort.DESCENDING)

The problem is when I add new Item 

well be added in the top but I can see it 

I need to scroll up manually 

Is there a way to scroll to the top automatically 

from realmAdapter or from realmRecyclerview automatically when there is any thing add to the recyclerview

**Comment by dimparf** [comment]
Hi
Faced with the same problem. How to scroll up or down after data upgrade?
There is a callback?
+1

**Comment by dimparf** [comment]
@MAJHOOOOOL i am use this trick:
RealmResults have method addChangeListener, I am scroll my recycleView on onChange callback.

**Comment by carlbenson** [comment]
How about using https://github.com/thorbenprimke/realm-recyclerview/blob/master/library/src/main/java/co/moonmonkeylabs/realmrecyclerview/RealmRecyclerView.java#L360 with 0 as argument?

**Comment by dashrathNumbertank** [comment]
How to set load more on top instead of bottom
