### ISSUE TITLE
Where and how to integrate limit mechanism ?

### ISSUE THREAD

**Issue by blackkara** [thorbenprimke/realm-recyclerview#75]
I just need listing latest inserted 30 entry instead of whole result-set when new one inserted.  Is there a painless way for this ?

**Comment by Zhuinden** [comment]
You would somehow need to redefine this part:

https://github.com/thorbenprimke/realm-recyclerview/blob/master/library/src/main/java/io/realm/RealmBasedRecyclerViewAdapter.java#L298-L311

Also you should provide `findAllSorted()` results where you sort by date of insertion.

**Comment by blackkara** [comment]
Thanks @Zhuinden
