### ISSUE TITLE
ScrollToPosition

### ISSUE THREAD

**Issue by MohammadRezaei92** [thorbenprimke/realm-recyclerview#80]
Recyclerview.smoothScrollToPosition(Pos); doesn't work.

**Comment by masilveira** [comment]
smoothScrollToPosition it works for me... Try too...

**Comment by MohammadRezaei92** [comment]
I get the position of item that I want to scroll to it and get it to smoothScrollToPosition as parameter but not happened

**Comment by masilveira** [comment]
try call this method on UiThread.. like this example:
        realmRecyclerView.post(new Runnable() {
            @Override
            public void run() {
                realmRecyclerView.smoothScrollToPosition(adapter.getItemCount());
            }
        });

**Comment by dimparf** [comment]
In my case I need not smoothing scrolling (( but it's not working...

**Comment by Farasy** [comment]
try

`realmRecyclerView.getRecycleView().scrollToPosition(position);`
