### ISSUE TITLE
Status 401 from the server

### ISSUE THREAD

**Issue by traabefi** [thorbenprimke/realm-recyclerview#82]
Hello, I am trying to compile your library but can't do it because jitpack doesn't allow me to do it. I am using compile 'com.github.thorbenprimke:realm-recycler-view:0.9.4'
Thanks

**Comment by ivkil** [comment]
You should use `'com.github.thorbenprimke:realm-recyclerview:0.9.4'` instead of
`'com.github.thorbenprimke:realm-recycler-view:0.9.4'`.

**Comment by reshadf** [comment]
Should change it in https://realm.io/news/android-realm-listview/ @ivkil

**Comment by thorbenprimke** [comment]
@reshadf - thanks for the note. I'll pass it on to get that updated.
