### ISSUE TITLE
RealmRecyclerView in NestedScrollView - layout_height="wrap_content"

### ISSUE THREAD

**Issue by rikochet** [thorbenprimke/realm-recyclerview#84]
When using `layout_height="wrap_content"` on a RealmRecyclerView in a NestedScrollView the height of the RealmRecyclerView appears to be 0.

When using a normal RecyclerView `wrap_content` works fine. I am guessing this has something to do with the FrameLayout wrapped around the RealmRecyclerView.

Are you aware of any way around this?

EDIT: I just realised this appear to be a similar request to issue #63.

**Comment by alextcn** [comment]
@rikochet yes, that's what I meant. Have you found any solution?

**Comment by dubiao** [comment]
Same problem here, and waiting for any solutions come out.
And also will PR as soon as I come out a good solution..
