### ISSUE TITLE
In Realm 0.89 realmResults.getTable() is deprecated and now removed

### ISSUE THREAD

**Issue by ahmadalibaloch** [thorbenprimke/realm-recyclerview#86]
Which if we turn on animate results, crashes the app saying `NoSuchMethod`found exception. 
In this file RealmBasedRecycleViewAdapter.class

```
 if(animateResults) {
                this.animatePrimaryColumnIndex = realmResults.getTable().getTable().getPrimaryKey();
                if(this.animatePrimaryColumnIndex == -1L) {
                    throw new IllegalStateException("Animating the results requires a primaryKey.");
                }
```

**Comment by StefanWegener** [comment]
Same if we use section headers. Does anyone has a solution?

**Comment by ahmadalibaloch** [comment]
Disable the animation be setting false to `animateIdType`, the 4th parameter in constructor, for the problem I mentioned. As is visible from my above comment the if condition check.

**Comment by thorbenprimke** [comment]
It's updated now. Animations work again with `compile 'com.github.thorbenprimke:realm-recyclerview:0.9.25'`.
