### ISSUE TITLE
Realmresults error

### ISSUE THREAD

**Issue by reshadf** [thorbenprimke/realm-recyclerview#88]
Hello,

I am getting 

> java.lang.NoSuchMethodError: No virtual method getRealm()Lio/realm/Realm; in class Lio/realm/RealmResults; or its super classes (declaration of 'io.realm.RealmResults' appears in /data/data/***/files/instant-run/dex/slice-io.realm-realm-android-library-2.0.2_65286432d702dab629d2322a66a4c74d2cf9a7e2-classes.dex)

Any ideas on how to fix this? I had to exclude the realm that came along with realm-recyclerview due to duplicate in my apk error.

```
compile ('com.github.thorbenprimke:realm-recyclerview:0.9.4') {
    exclude module: 'realm-android'
}
```

**Comment by thorbenprimke** [comment]
I have updated to Realm 2.2.1 so you just need to update the dependency. 

`compile 'com.github.thorbenprimke:realm-recyclerview:0.9.25'`
